### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by bnbabu55** [imranhsayed/react-wordpress-theme#10]
I did create an issue under phoenix-theme also for this as I was trying to use that theme and encountered this error. I am creating this here also as this is specifically for this plugin, you can close one of these as you find appropriate.

I am using, WP 5.4.2, php 7.4.7.

Fatal error: Uncaught Error: Class 'Headless_CMS\Inc\Plugin' not found in C:\Utilities\laragon\www\smrwp\wp-content\plugins\headless-cms\headless-cms.php:33 Stack trace: #0 C:\Utilities\laragon\www\smrwp\wp-content\plugins\headless-cms\headless-cms.php(36): headless_cms_features_plugin_loader() #1 C:\Utilities\laragon\www\smrwp\wp-admin\includes\plugin.php(2255): include('C:\\Utilities\\la...') #2 C:\Utilities\laragon\www\smrwp\wp-admin\plugins.php(177): plugin_sandbox_scrape('headless-cms/he...') #3 {main} thrown in C:\Utilities\laragon\www\smrwp\wp-content\plugins\headless-cms\headless-cms.php on line 33

Thanks for your help in advance.

**Comment by RangerCoder99** [comment]
Same here! 

Seems this function is tricking the error:
`function headless_cms_features_plugin_loader() {
	\Headless_CMS\Features\Inc\Plugin::get_instance();
}
`

**Comment by imranhsayed** [comment]
Please download the latest version from WordPress org
https://wordpress.org/plugins/headless-cms/
